FROM node:lts AS base

WORKDIR /usr/src/app

COPY ./client/package*.json ./

RUN npm install

COPY ./client .

FROM base AS development

EXPOSE 5173

CMD ["npm", "run", "dev"]
# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

FROM base AS build

RUN npm run build
