FROM python:3.12-slim AS base

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y gcc

COPY ./server/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server .

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

CMD ["flask", "run", "--host=0.0.0.0", "--debug"]
